name: flutter_maths_mingle_app
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=3.1.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  connectivity_plus: ^6.0.3
  dots_indicator: ^3.0.0
  pinput: ^4.0.0
  path_provider: ^2.1.2
  timer_count_down: ^2.2.2
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  pin_code_fields: ^8.0.1
  country_pickers: ^3.0.1
  smooth_page_indicator: ^1.1.0
  flutter_svg_provider:
  sms_autofill: ^2.3.1
  dotted_line: ^3.2.2
  #  intl_phone_field: ^3.2.0
  google_maps_flutter:
  percent_indicator: ^4.2.3
  syncfusion_flutter_sliders: ^25.2.5
  flutter_switch: ^0.3.2
  flutter_card_swiper: ^7.0.0
  dio: ^5.4.3+1

  intl: ^0.19.0
  firebase_core: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
    - family: Outfit
      fonts:
        - asset: assets/fonts/OutfitRegular.ttf
          weight: 400
    - family: Satoshi
      fonts:
        - asset: assets/fonts/SatoshiBold.ttf
          weight: 700
        - asset: assets/fonts/SatoshiRegular.ttf
          weight: 400
