// import 'controller/make_friends_profile_details_controller.dart';import 'package:flutter/material.dart';import 'package:flutter_maths_mingle_app/core/app_export.dart';import 'package:flutter_maths_mingle_app/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:flutter_maths_mingle_app/widgets/app_bar/custom_app_bar.dart';import 'package:flutter_maths_mingle_app/widgets/custom_elevated_button.dart';import 'package:flutter_maths_mingle_app/widgets/custom_icon_button.dart';import 'package:flutter_maths_mingle_app/widgets/custom_outlined_button.dart';class MakeFriendsProfileDetailsScreen extends GetWidget<MakeFriendsProfileDetailsController> {const MakeFriendsProfileDetailsScreen({Key? key}) : super(key: key);
//
// @override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 16.v), child: Container(padding: EdgeInsets.symmetric(horizontal: 23.h), child: Column(children: [Container(margin: EdgeInsets.only(left: 1.h), padding: EdgeInsets.all(16.h), decoration: AppDecoration.outlineErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 299.v, width: 295.h, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgRectangle249663, height: 299.v, width: 295.h, radius: BorderRadius.circular(8.h), alignment: Alignment.center), Align(alignment: Alignment.center, child: Container(padding: EdgeInsets.symmetric(horizontal: 8.h, vertical: 5.v), decoration: AppDecoration.gradientErrorContainerToErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), Align(alignment: Alignment.centerRight, child: SizedBox(height: 48.adaptSize, width: 48.adaptSize, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: SizedBox(height: 48.adaptSize, width: 48.adaptSize, child: CircularProgressIndicator(value: 0.5, strokeWidth: 3.h))), Align(alignment: Alignment.center, child: Text("lbl_50".tr, style: theme.textTheme.labelLarge))]))), SizedBox(height: 214.v), Text("lbl_2_5_km_away".tr, style: CustomTextStyles.bodyLargeWhiteA700)])))])), SizedBox(height: 9.v), Text("lbl_dominic_grimsh".tr, style: CustomTextStyles.titleMedium17), SizedBox(height: 3.v), Text("lbl_william".tr, style: theme.textTheme.bodyMedium), SizedBox(height: 15.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomOutlinedButton(height: 46.v, width: 138.h, text: "lbl_chat".tr, buttonTextStyle: CustomTextStyles.titleMediumPrimary16, onPressed: () {onTapChat();}), CustomElevatedButton(height: 46.v, width: 137.h, text: "lbl_add_friend".tr, buttonTextStyle: CustomTextStyles.titleMediumWhiteA700)])])), SizedBox(height: 24.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 1.h), child: Text("lbl_about".tr, style: theme.textTheme.titleMedium))), SizedBox(height: 9.v), SizedBox(width: 327.h, child: Text("msg_a_good_listener".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodyMedium!.copyWith(height: 1.40))), SizedBox(height: 24.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 1.h), child: Text("lbl_interest".tr, style: theme.textTheme.titleMedium))), SizedBox(height: 16.v), _buildFootballOne(), SizedBox(height: 8.v), _buildFootball()])))))); }
// /// Section Widget
// PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.fromLTRB(24.h, 16.v, 311.h, 16.v), onTap: () {onTapArrowLeft();}), styleType: Style.bgShadow); }
// /// Section Widget
// Widget _buildFootballOne() { return Padding(padding: EdgeInsets.only(left: 1.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Padding(padding: EdgeInsets.only(right: 10.h), child: CustomIconButton(height: 67.adaptSize, width: 67.adaptSize, padding: EdgeInsets.all(17.h), child: CustomImageView(imagePath: ImageConstant.imgFootball1)))), Expanded(child: Padding(padding: EdgeInsets.symmetric(horizontal: 10.h), child: CustomIconButton(height: 67.adaptSize, width: 67.adaptSize, padding: EdgeInsets.all(17.h), child: CustomImageView(imagePath: ImageConstant.imgLeaf1)))), Expanded(child: Padding(padding: EdgeInsets.symmetric(horizontal: 10.h), child: CustomIconButton(height: 67.adaptSize, width: 67.adaptSize, padding: EdgeInsets.all(17.h), child: CustomImageView(imagePath: ImageConstant.imgPen1)))), Expanded(child: Padding(padding: EdgeInsets.only(left: 10.h), child: CustomIconButton(height: 67.adaptSize, width: 67.adaptSize, padding: EdgeInsets.all(17.h), child: CustomImageView(imagePath: ImageConstant.imgVinylRecord1))))])); }
// /// Section Widget
// Widget _buildFootball() { return Padding(padding: EdgeInsets.only(left: 7.h, right: 14.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_football".tr, textAlign: TextAlign.center, style: CustomTextStyles.bodyMediumErrorContainer), Spacer(flex: 31), Text("lbl_nature".tr, textAlign: TextAlign.center, style: CustomTextStyles.bodyMediumErrorContainer), Spacer(flex: 33), Text("lbl_writing".tr, textAlign: TextAlign.center, style: CustomTextStyles.bodyMediumErrorContainer), Spacer(flex: 35), Text("lbl_music".tr, textAlign: TextAlign.center, style: CustomTextStyles.bodyMediumErrorContainer)])); }
//
// /// Navigates to the previous screen.
// onTapArrowLeft() { Get.back(); }
// /// Navigates to the firstTimeChatScreen when the action is triggered.
// onTapChat() { Get.toNamed(AppRoutes.firstTimeChatScreen, ); }
//  }
