// import '../make_friends_profile_details_scroll_screen/widgets/column2_item_widget.dart';import '../make_friends_profile_details_scroll_screen/widgets/gendertext_item_widget.dart';import 'controller/make_friends_profile_details_scroll_controller.dart';import 'dart:async';import 'models/column2_item_model.dart';import 'models/gendertext_item_model.dart';import 'package:flutter/material.dart';import 'package:flutter_maths_mingle_app/core/app_export.dart';import 'package:flutter_maths_mingle_app/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:flutter_maths_mingle_app/widgets/app_bar/appbar_subtitle.dart';import 'package:flutter_maths_mingle_app/widgets/app_bar/custom_app_bar.dart';import 'package:google_maps_flutter/google_maps_flutter.dart';
// // ignore_for_file: must_be_immutable
// class MakeFriendsProfileDetailsScrollScreen extends GetWidget<MakeFriendsProfileDetailsScrollController> {MakeFriendsProfileDetailsScrollScreen({Key? key}) : super(key: key);
//
// Completer<GoogleMapController> googleMapController = Completer();
//
// @override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 23.h, vertical: 16.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 1.h), child: Text("lbl_about".tr, style: theme.textTheme.titleMedium)), SizedBox(height: 9.v), Container(width: 327.h, margin: EdgeInsets.only(left: 1.h), child: Text("msg_a_good_listener".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodyMedium!.copyWith(height: 1.40))), SizedBox(height: 24.v), Padding(padding: EdgeInsets.only(left: 1.h), child: Text("lbl_interest".tr, style: theme.textTheme.titleMedium)), SizedBox(height: 16.v), _buildColumn(), SizedBox(height: 22.v), _buildGenderText(), SizedBox(height: 24.v), Padding(padding: EdgeInsets.only(left: 1.h), child: Text("lbl_location".tr, style: theme.textTheme.titleMedium)), SizedBox(height: 17.v), _buildMap(), SizedBox(height: 5.v)])))); }
// /// Section Widget
// PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 64.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h, top: 16.v, bottom: 16.v), onTap: () {onTapArrowLeft();}), title: AppbarSubtitle(text: "lbl_about".tr, margin: EdgeInsets.only(left: 16.h)), styleType: Style.bgShadow); }
// /// Section Widget
// Widget _buildColumn() { return SizedBox(height: 97.v, child: Obx(() => ListView.separated(padding: EdgeInsets.only(left: 1.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 20.h);}, itemCount: controller.makeFriendsProfileDetailsScrollModelObj.value.column2ItemList.value.length, itemBuilder: (context, index) {Column2ItemModel model = controller.makeFriendsProfileDetailsScrollModelObj.value.column2ItemList.value[index]; return Column2ItemWidget(model);}))); }
// /// Section Widget
// Widget _buildGenderText() { return SizedBox(height: 118.v, child: Obx(() => ListView.separated(padding: EdgeInsets.only(left: 1.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 17.h);}, itemCount: controller.makeFriendsProfileDetailsScrollModelObj.value.gendertextItemList.value.length, itemBuilder: (context, index) {GendertextItemModel model = controller.makeFriendsProfileDetailsScrollModelObj.value.gendertextItemList.value[index]; return GendertextItemWidget(model);}))); }
// /// Section Widget
// Widget _buildMap() { return Container(height: 148.v, width: 327.h, margin: EdgeInsets.only(left: 1.h), child: GoogleMap(mapType: MapType.normal, initialCameraPosition: CameraPosition(target: LatLng(37.43296265331129, -122.08832357078792), zoom: 14.4746), onMapCreated: (GoogleMapController controller) {googleMapController.complete(controller);}, zoomControlsEnabled: false, zoomGesturesEnabled: false, myLocationButtonEnabled: false, myLocationEnabled: false)); }
//
// /// Navigates to the previous screen.
// onTapArrowLeft() { Get.back(); }
//  }
