// import 'controller/home_search_partners_swipe_left_tab_container_controller.dart';import 'package:flutter/material.dart';import 'package:flutter_maths_mingle_app/core/app_export.dart';import 'package:flutter_maths_mingle_app/presentation/home_search_partners_page/home_search_partners_page.dart';import 'package:flutter_maths_mingle_app/presentation/home_search_partners_swipe_left_page/home_search_partners_swipe_left_page.dart';import 'package:flutter_maths_mingle_app/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:flutter_maths_mingle_app/widgets/app_bar/appbar_trailing_iconbutton_one.dart';import 'package:flutter_maths_mingle_app/widgets/app_bar/custom_app_bar.dart';class HomeSearchPartnersSwipeLeftTabContainerScreen extends GetWidget<HomeSearchPartnersSwipeLeftTabContainerController> {const HomeSearchPartnersSwipeLeftTabContainerScreen({Key? key}) : super(key: key);
//
// @override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 32.v), Container(height: 29.v, width: 286.h, margin: EdgeInsets.only(right: 25.h), child: TabBar(controller: controller.tabviewController, labelPadding: EdgeInsets.zero, labelColor: theme.colorScheme.primary, labelStyle: TextStyle(fontSize: 15.fSize, fontFamily: 'Satoshi', fontWeight: FontWeight.w700), unselectedLabelColor: appTheme.gray700, unselectedLabelStyle: TextStyle(fontSize: 15.fSize, fontFamily: 'Satoshi', fontWeight: FontWeight.w400), indicatorColor: theme.colorScheme.primary, tabs: [Tab(child: Text("lbl_make_friends".tr)), Tab(child: Text("lbl_search_partners".tr))])), SizedBox(height: 634.v, child: TabBarView(controller: controller.tabviewController, children: [HomeSearchPartnersSwipeLeftPage(), HomeSearchPartnersPage()]))])))); }
// /// Section Widget
// PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 64.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h, top: 16.v, bottom: 16.v), onTap: () {onTapArrowLeft();}), actions: [AppbarTrailingIconbuttonOne(imagePath: ImageConstant.imgFavoriteErrorcontainer, margin: EdgeInsets.only(left: 24.h, top: 16.v, right: 16.h)), AppbarTrailingIconbuttonOne(imagePath: ImageConstant.imgUpload, margin: EdgeInsets.only(left: 16.h, top: 16.v, right: 40.h), onTap: () {onTapUpload();})], styleType: Style.bgShadow); }
//
// /// Navigates to the previous screen.
// onTapArrowLeft() { Get.back(); }
// /// Navigates to the discoverFilterScreen when the action is triggered.
// onTapUpload() { Get.toNamed(AppRoutes.discoverFilterScreen, ); }
//  }
