// import 'controller/connect_make_friends_controller.dart';import 'package:flutter/material.dart';import 'package:flutter_maths_mingle_app/core/app_export.dart';import 'package:flutter_maths_mingle_app/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:flutter_maths_mingle_app/widgets/app_bar/custom_app_bar.dart';import 'package:flutter_maths_mingle_app/widgets/custom_elevated_button.dart';import 'package:flutter_maths_mingle_app/widgets/custom_icon_button.dart';import 'package:flutter_maths_mingle_app/widgets/custom_outlined_button.dart';import 'package:flutter_maths_mingle_app/widgets/custom_text_form_field.dart';class ConnectMakeFriendsScreen extends GetWidget<ConnectMakeFriendsController> {const ConnectMakeFriendsScreen({Key? key}) : super(key: key);
//
// @override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 23.h, vertical: 32.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildGreetingColumn(), SizedBox(height: 39.v), Padding(padding: EdgeInsets.only(left: 1.h), child: Text("lbl_interest".tr, style: theme.textTheme.titleLarge)), SizedBox(height: 16.v), _buildFrameRow(), SizedBox(height: 23.v), Container(width: 308.h, margin: EdgeInsets.only(left: 1.h, right: 19.h), child: Text("msg_you_have_3_things".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodyMedium!.copyWith(height: 1.40))), SizedBox(height: 5.v)])), bottomNavigationBar: _buildMessage())); }
// /// Section Widget
// PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.fromLTRB(24.h, 16.v, 311.h, 16.v), onTap: () {onTapArrowLeft();}), styleType: Style.bgShadow); }
// /// Section Widget
// Widget _buildGreetingEditText() { return CustomTextFormField(width: 89.h, controller: controller.greetingEditTextController, hintText: "lbl_hello".tr, hintStyle: CustomTextStyles.bodyMediumErrorContainer, alignment: Alignment.centerRight, contentPadding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 5.v), borderDecoration: TextFormFieldStyleHelper.outlineErrorContainer, fillColor: appTheme.whiteA700); }
// /// Section Widget
// Widget _buildGreetingTwoEditText() { return CustomTextFormField(width: 70.h, controller: controller.greetingTwoEditTextController, hintText: "lbl_hii".tr, hintStyle: CustomTextStyles.bodyMediumErrorContainer, textInputAction: TextInputAction.done, contentPadding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 5.v), borderDecoration: TextFormFieldStyleHelper.outlineErrorContainer, fillColor: appTheme.whiteA700); }
// /// Section Widget
// Widget _buildGreetingColumn() { return Container(height: 294.v, width: 327.h, margin: EdgeInsets.only(left: 1.h), child: Stack(alignment: Alignment.bottomLeft, children: [CustomImageView(imagePath: ImageConstant.imgRectangle2555205x162, height: 162.adaptSize, width: 162.adaptSize, radius: BorderRadius.circular(81.h), alignment: Alignment.topRight), CustomImageView(imagePath: ImageConstant.imgRectangle2556205x162, height: 162.adaptSize, width: 162.adaptSize, radius: BorderRadius.circular(81.h), alignment: Alignment.bottomLeft), Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(left: 46.h, right: 36.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [_buildGreetingEditText(), SizedBox(height: 100.v), _buildGreetingTwoEditText()])))])); }
// /// Section Widget
// Widget _buildFrameRow() { return Padding(padding: EdgeInsets.only(left: 1.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(right: 10.h, bottom: 1.v), child: _buildFrameColumn(nature: "lbl_football".tr)), Padding(padding: EdgeInsets.only(left: 10.h, right: 10.h, bottom: 1.v), child: _buildFrameColumn(nature: "lbl_nature".tr)), Padding(padding: EdgeInsets.symmetric(horizontal: 10.h), child: _buildFrameColumn(nature: "lbl_writing".tr)), Padding(padding: EdgeInsets.only(left: 10.h, bottom: 1.v), child: _buildFrameColumn(nature: "lbl_music".tr))])); }
// /// Section Widget
// Widget _buildMessageButton() { return CustomOutlinedButton(width: 154.h, text: "lbl_message".tr, onPressed: () {onTapMessageButton();}); }
// /// Section Widget
// Widget _buildLetsTalkButton() { return CustomElevatedButton(width: 153.h, text: "lbl_let_s_talk".tr, margin: EdgeInsets.only(left: 20.h), onPressed: () {onTapLetsTalkButton();}); }
// /// Section Widget
// Widget _buildMessage() { return Container(margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 24.v), decoration: AppDecoration.white, child: Row(mainAxisAlignment: MainAxisAlignment.center, mainAxisSize: MainAxisSize.min, children: [_buildMessageButton(), _buildLetsTalkButton()])); }
// /// Common widget
// Widget _buildFrameColumn({required String nature}) { return Expanded(child: SizedBox(width: double.maxFinite, child: Column(children: [CustomIconButton(height: 67.adaptSize, width: 67.adaptSize, padding: EdgeInsets.all(17.h), child: CustomImageView(imagePath: ImageConstant.imgLeaf1)), SizedBox(height: 8.v), Text(nature, style: CustomTextStyles.bodyMediumErrorContainer.copyWith(color: theme.colorScheme.errorContainer.withOpacity(1)))]))); }
//
// /// Navigates to the previous screen.
// onTapArrowLeft() { Get.back(); }
// /// Navigates to the firstTimeChatScreen when the action is triggered.
// onTapMessageButton() { Get.toNamed(AppRoutes.firstTimeChatScreen, ); }
// /// Navigates to the firstTimeChatOneScreen when the action is triggered.
// onTapLetsTalkButton() { Get.toNamed(AppRoutes.firstTimeChatOneScreen, ); }
//  }
